services:
  jla:
    build: .
    restart: unless-stopped
    container_name: jla
    volumes:
      - ./jla-alerts:/usr/share/nginx/html/jla-alerts
      - ./jla-dashboard:/usr/share/nginx/html/jla-dashboard
      - ./jla-progress:/usr/share/nginx/html/jla-progress
      - ./jla-splash:/usr/share/nginx/html/jla-splash
      - ./jla-standings:/usr/share/nginx/html/jla-standings
      - ./favicon.ico:/usr/share/nginx/html/favicon.ico
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.jla.rule=Host(`jla.local`)"
      - "traefik.http.services.jla.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true
